2019-01-24 21:22:00,914 INFO: Microblog startup [in /home/piotr/Projects/pydocker/web/__init__.py:38]
2019-01-24 21:22:06,101 ERROR: Exception on /index [GET] [in /home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/piotr/Projects/pydocker/web/routes.py", line 20, in index
    return render_template('index2.html', title='Home', tickers_subscriptions = subscriptions)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index2.html
2019-01-24 21:22:09,467 ERROR: Exception on /index [GET] [in /home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/piotr/Projects/pydocker/web/routes.py", line 20, in index
    return render_template('index2.html', title='Home', tickers_subscriptions = subscriptions)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index2.html
2019-01-24 21:22:11,508 ERROR: Exception on /index [GET] [in /home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/piotr/Projects/pydocker/web/routes.py", line 20, in index
    return render_template('index2.html', title='Home', tickers_subscriptions = subscriptions)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/piotr/Projects/pydocker/pydocker_env/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index2.html
2019-01-26 22:17:36,848 INFO: Microblog startup [in /home/piotr/Projects/pydocker/web/__init__.py:38]
